### ISSUE TITLE
MD5 checksum is unsafe for a large number of files

### ISSUE THREAD

**Issue by dnmfarrell** [mcmillhj/File-Dedup#1]
You may get collisions, so might want to add another check like the file size in bytes. I.e. if the bytes and the checksum match, then it's more likely to be a dupe.

**Comment by mcmillhj** [comment]
Really good point. I knew that I would have to change the process in some way because I didn't think MD5 was reliable enough. I mainly chose it because it was core and it is fast. Thanks for pointing this out. I should have a patch in soon.

**Comment by mcmillhj** [comment]
Hmm it appears that there exists a known pair of 128 byte strings that both have the same MD5 checksum: http://www.mscs.dal.ca/~selinger/md5collision/

**Comment by dnmfarrell** [comment]
Switch to SHA1?

**Comment by mcmillhj** [comment]
I think that is probably the most reasonably decision. It would avoid the `-s` check as well since the likelihood of a collision is very small.

**Comment by mcmillhj** [comment]
Thanks  for the feedback! This was the first issue I have ever had opened against my own code.

**Comment by dnmfarrell** [comment]
Np!
